apiVersion: skaffold/v2beta9
kind: Config
build:
  artifacts:
  - image: cowsay-server
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
    - ./cowsay-config/*
profiles:
  - name: minikube
    activation:
      - kubeContext: minikube
    deploy:
      kubectl:
        manifests:
        - ./cowsay-config/*
